### ISSUE TITLE
Rate-Limit support for groups

### ISSUE THREAD

**Issue by manast** [taskforcesh/bullmq-pro-support#1]
# Motivation

Groups allows to process jobs in order relative to their group ids. However the workers will process jobs as fast as they can. Groups many times represent users in a system, which often times require rate limiting per user.

# Solution

A rate limit per group, so that every group is limited based on their jobs independently on the rest of the system. It should still be possible to combine the rate limits per group with a global rate limit if needed.

The API for determining the limit is provided at the job producer level when adding a job to a group:

```ts
  import { QueuePro } from 'bullmq-pro'
  
  const queue = new QueuePro();

  const job1 = await queue.add('test', { foo: 'bar1' }, {
    group: {
      id: 1,
      limit: {
       max: 250,
       duration: 3000,
      }
    },
  });
  
  const job2 = await queue.add('test', { foo: 'bar2' }, {
    group: {
      id: 2,
      limit: {
        max: 100,
        duration: 4000,
      }
    },
  });
```

As seen in the example the rate limiters are independent of each other. An important consideration is the effects of changing the limit settings per job added to a group. The worker will always try to honor the setting belonging to the job it is about to process and if so rate limit it.

In standard Bull/BullMQ, rate limit is achieved by delaying the jobs. The proposed solution is based instead on a new "rate-limited" status, which is maintained per group. This results in a simpler and more performant solution than the one based on delayed jobs.

**Comment by lukepolo** [comment]
Is this already completed?

**Comment by manast** [comment]
Not yet, still in the works. A priority for you?

**Comment by lukepolo** [comment]
shortly it will be a high priority

**Comment by manast** [comment]
Implemented in v1.2.0.

**Comment by lukepolo** [comment]
Awesome!!! We will be trying this out here soon ! Thanks for the hard work on this!

**Comment by SirBernardPhilip** [comment]
Hey! Love this feature, it really solves one of our current use cases, nevertheless I have found that after the rate limit expires and retries the job that threw the RateLimit error all the other jobs that had to be run after that fail to run. Is this happening to anyone else?

**Comment by dginzbourg** [comment]
I'm using this feature and RT exception doesn't affect any other job. But I'm using groups in combination with RT, maybe your case is different.

**Comment by SirBernardPhilip** [comment]
I am also using groups, it seems that after the RT exception the job that caused is retried after the cooldown (I set a total of 3ish minutes cooldown for testing purposes) but other jobs that the group still has are not picked up. I have a basic GUI on VSCode to see the content of Redis and I can still see information pertaining to the missing job, here are some captures if it helps.

All the different keys:
![image](https://user-images.githubusercontent.com/16084918/216019948-21b1ce92-1dd8-4b1e-bdf8-81ede57ae6a5.png)

Content of bull:IMPORT_EVERNOTE:events
![image](https://user-images.githubusercontent.com/16084918/216019146-819c919b-8556-4104-8de4-a9e42ea2c5e6.png)

Content of bull:IMPORT_EVERNOTE:3
![image](https://user-images.githubusercontent.com/16084918/216020667-cd9d0fa3-17bb-4f17-bc44-86707eecdcf2.png)

Content of bull:IMPORT_EVERNOTE:groups:active:count
![image](https://user-images.githubusercontent.com/16084918/216020882-7ff6654e-e805-483d-ab8c-bde3df85a68d.png)

I don't know if these are of any use, but I do see that the events show that the queue is drained when there is still one more job (3) to be processed and the group still seems to be active. Is there any setting or something that I do incorrectly that prompts this behavior or is this a bug?

**Comment by manast** [comment]
@SirBernardPhilip could you open a new issue, so that we can track this properly? Also, when you say rate-limit do you mean per group or global? It would be great if you could produce some minimal test code that shows what you mean, that would be really helpful to understand the case and to investigate a possible bug if any.

**Comment by manast** [comment]
Btw, taskforce.sh supports groups, so you can also use it to debug and understand better what is going on.

**Comment by SirBernardPhilip** [comment]
@manast I created a new issue and some test code, let me know if that helps reproduce it.

**Comment by rorhug** [comment]
Is this feature available in v5, v5 pro or not at all anymore? The docs say it's no longer available from 3 onwards so curious what version you're talking about that has the feature in 2023.

https://docs.bullmq.io/guide/rate-limiting#group-keys

**Comment by lukepolo** [comment]
its a pro feature : https://docs.bullmq.io/bullmq-pro/groups/rate-limiting

**Comment by rorhug** [comment]
Makes sense however is there a code example for limiting based on a group key?

The link in the [non-pro docs](https://docs.bullmq.io/bullmq-pro/groups/rate-limiting) above says it was removed for performance reasons: "From BullMQ 3.0 and onwards, group keys support is removed to improve global rate limit, so the information below is only valid for older versions."

I've seen https://docs.bullmq.io/bullmq-pro/groups/concurrency and https://docs.bullmq.io/bullmq-pro/groups/max-group-size but i don't understand why you would be specifying `maxSize` on every `queue.add`. 

My goal is to specify a concurrency limit for custom group key. If the limit is hit when adding a new job, either throwing or queuing for when there is space are reasonable outcomes assuming they're documented.

Is that specifically still available?

**Comment by manast** [comment]
You choose the rate limit as specified here: https://docs.bullmq.io/bullmq-pro/groups/rate-limiting
Then you just add jobs specifying to which group you want to add the job to (https://docs.bullmq.io/bullmq-pro/groups), and they will then get rate-limited per group. Unfortunatelly it is not possible to specify a different rate limit setting per group, the same setting will apply to all the groups.

**Comment by rorhug** [comment]
Okay - thanks for the clarification @manast 

For the `maxSize` of the group - how come you would pass that when queueing a job?  I guess, there is no explicit group creation method.

If I `.add` once with `maxSize` but then omit it on subsequent `.add`s, would it enforce whatever the last `maxSize` seen was? or only as far as jobs that had it included are still in the queue?

**Comment by manast** [comment]
> For the `maxSize` of the group - how come you would pass that when queueing a job? I guess, there is no explicit group creation method.

You don't, you specify it in the worker settings as in the examples above:
```ts
import { WorkerPro } from '@taskforcesh/bullmq-pro';

const worker = new WorkerPro('myQueue', processFn, {
    group: {
      limit: {
        max: 100,  // Limit to 100 jobs per second per group
        duration: 1000,
      }
    },
    connection
});
```

**Comment by rorhug** [comment]
Right - that makes sense, but what i'm talking about is in this page https://docs.bullmq.io/bullmq-pro/groups/max-group-size

What does the `maxSize: 7` here mean for the one job being queued?

```
import { QueuePro, GroupMaxSizeExceededError } from '@taskforcesh/bullmq-pro';

const queue = new QueuePro('myQueue', { connection });
const groupId = 'my group';
try {
  await queue.add('paint', { foo: 'bar' }, {
      group: {
        id: groupId,
        maxSize: 7,
      },
    });
} catch (err) {
  if (err instanceof GroupMaxSizeExceededError){
    console.log(`Job discarded for group ${groupId}`)
  } else {
    throw err;
  }
}
```

It's in the reference [here](https://api.bullmq.pro/interfaces/v6.JobsProOptions.html) as the options to [add](https://api.bullmq.pro/interfaces/v6.JobsProOptions.html#group)

**Comment by manast** [comment]
That means that if there are more than "maxSize" jobs already queued in a given group, you will get an exception and the job will be ignored.
I am happy to continue this conversation in a new discussion or issue to avoid spamming with messages to the rest of the people marked as observers of this issue.

**Comment by vlrevolution** [comment]
Is it possible to have a global rate limit, let's say 200 requests per minute, and then for each group (user) we set also a lower rate limit like 5 requests per minute, does this make sense? To ensure fair use, but always to stay under the global 200 req/min as well.

**Comment by manast** [comment]
@vlrevolution You should be able to achieve this by setting a standard rate-limit on the queue, and then a rate-limit for the groups.

**Comment by vlrevolution** [comment]
> That means that if there are more than "maxSize" jobs already queued in a given group, you will get an exception and the job will be ignored. I am happy to continue this conversation in a new discussion or issue to avoid spamming with messages to the rest of the people marked as observers of this issue.

Thanks for the reply.

We cannot dynamically set different rate limits for each user (group)?

**Comment by manast** [comment]
You have a lot of options, you can use manual rate limit so that you can decide at the time of processing the job if you want to rate limit the group: https://docs.bullmq.io/bullmq-pro/groups/rate-limiting or you can use per group rate limits: https://docs.bullmq.io/bullmq-pro/groups/local-group-concurrency

**Comment by ben-at-cursor** [comment]
@manast Relatedly to this thread, could I get clarity from a BullMQ maintainer on whether the group max size includes active jobs for that group? That is, assuming a group max size of 1, if I have one job J for group G active and another job J' comes in for group G, will that incoming job J' get dropped or enqueued?
