### ISSUE TITLE
Pausing a Single Group

### ISSUE THREAD

**Issue by lukepolo** [taskforcesh/bullmq-pro-support#10]
Is it possible to pause a single group? 

We are trying to rate limit our group to only ever be running a max of x concurrent jobs at a time. 

Related #9

**Comment by roggervalf** [comment]
hi @lukepolo, now it is possible to pause a single group, you should check https://api.bullmq.pro/classes/Queue.html#pauseGroup and https://api.bullmq.pro/classes/Queue.html#resumeGroup

**Comment by lukepolo** [comment]
Awesome work! Props to the team!
