### ISSUE TITLE
Determine number of jobs in a Group

### ISSUE THREAD

**Issue by itjustwerks** [taskforcesh/bullmq-pro-support#11]
I've been banging my head on a wall not seeing the line in the documentation that says the pending jobs in a Group will not show up in the Waiting queue (looking in Taskforce). I have a use case where from a support perspective I might need to be able to let a user know how many jobs are backed up in their specific "virtual" queue. Is there a way to get insight into this? I'm assuming it can be accessed in Redis directly. I'm a total newb with Redis and have only set it up enough to get it connected here. It's a black box otherwise. Thanks!

**Comment by manast** [comment]
Here are apis that returns all the data related to groups: https://api.bullmq.pro/classes/Queue.html#getGroupJobs
