### ISSUE TITLE
Problem with moveToFinished LUA script

### ISSUE THREAD

**Issue by loicsimon** [taskforcesh/bullmq-pro-support#12]
Hi,

We're testing BullMQ Pro v1.3.2 with BullMQ v1.77.0 as a dependency and we have some problems with our workers.

When a job completes, the script called 'moveToFinished-12.lua' is run.
At the end it tries to call `trimEvents` like this : `trimEvents(KEYS[11], KEYS[6])`.

From our understanding, `trimEvents()` comes from BullMQ classic and it shall be called like this : `trimEvents(KEYS[11], KEYS[4])` as `KEYS[4]` is `stream events key` whereas `KEYS[6]` is `rate limiter key`.

Did we do something wrong or is this a real issue?

Thank you!

**Comment by roggervalf** [comment]
@loicsimon could you please try the last version, it should fix this issue
