### ISSUE TITLE
Support to manually rate-limit jobs

### ISSUE THREAD

**Issue by manast** [taskforcesh/bullmq-pro-support#19]
There are some special cases that would benefit from manually rate limit a queue.

## Rate limit based on a call to a third party API
Sometimes it is not possible to have a fixed rate limit, and instead what is required is to rate limit a queue when a call to the third party returns HTTP 429 Too Many Requests or similar.

## Global rate limiter
In other situations it is useful to have a rate limiter that is global, so that it can be shared among queues. For example, maybe there are several queues doing different jobs but all of them need to access a third party api that can rate limit them, so it means that once the api has reached the maximum amount of calls, all the queues that depend on that API should also be rate limited.

**Comment by dginzbourg** [comment]
It'd be nice to have abstraction that allows to define the desired rate-limiting configuration and support dynamic throttling using job error similar to 429 (could be special result return value). Job has custom code and doesn't equal 1 api call. Could you consider implementing something similar to https://eng.lyft.com/announcing-ratelimit-c2e8f3182555?gi=ba6ffdb5a348, i.e. support hierarchic definition kept on job metadata including group level? This will allow wide range of flexible scenarios.

**Comment by manast** [comment]
If a job includes other async calls, but only 1 API call should be rate limited, then it is better to split the job into smaller jobs. In BullMQ we just released the possibility to set the rate limiter dynamically, however this is only possible for the globa rate-limit, but we will provide a similar mechanism for groups: https://blog.taskforce.sh/rate-limit-recipes-in-nodejs-using-bullmq/

**Comment by roggervalf** [comment]
This feature is available for groups and in a global way
