### ISSUE TITLE
Jobs cancellation support with observables

### ISSUE THREAD

**Issue by manast** [taskforcesh/bullmq-pro-support#2]
Currently it is not possible to cancel a running job. This is in part because promises cannot be cancelled at the moment (unless using non standard methods such as the ones used by Bluebird).
However, if the processor functions were allowed to return an Observable, then it would be fully possible to cancel the processor in a clean and standard way.

Furthermore, when using observables it would also be possible to implement workers that runs things like XState https://xstate.js.org/docs/recipes/rxjs.html. 

The observable stream can be stored in the job so that if the job is cancelled for any reason, it would be possible to resume the "state" by taking the last observable value emitted.

**Comment by manast** [comment]
Implemented in v1.1.0

**Comment by dturton** [comment]
Is there an example for this pattern?

**Comment by manast** [comment]
Hi @dturton I just improved the documentation regarding Observables, including cancelation: https://docs.bullmq.io/bullmq-pro/observables.
We are also planning will also implement cancelation based on the JobId. This is a much more complex case since it requires a communication channel between the Worker and the client requesting the cancelation.

**Comment by dturton** [comment]
Hi @manast looking over the additional documentation. How do we then return a jobResult if using observables?

**Comment by manast** [comment]
@dturton as in the examples here: https://docs.bullmq.io/bullmq-pro/observables just call ```subscriber.next("result")```
