### ISSUE TITLE
getting group job issue

### ISSUE THREAD

**Issue by for2gles** [taskforcesh/bullmq-pro-support#24]
First of all, thank you for your help

I found below issues

- [ ]  If I use `group`, I cannot get any waiting jobs using `queue.getJobs('wait')` or `queue.getJobs('waiting')` or `queue.getWaiting()`
- [ ] The type of the result from `queue.getJobs(anything)` is `Job<anything>` not `JobPro<anything>`
- [ ] queue.getGroupJobs() has no option to filter with job types

**Comment by manast** [comment]
@for2gles 

We have added a couple of methods that would help you in these tasks: https://api.bullmq.pro/classes/Queue.html#getGroupsByStatus
As mentioned yesterday we have also new support for Groups in the dashboard. Unfortunately we found a small error that we are fixing right now, we are releasing ASAP.
