### ISSUE TITLE
group rate-limit settings isn't avaialble in job.add api

### ISSUE THREAD

**Issue by dginzbourg** [taskforcesh/bullmq-pro-support#27]
Hi
I'm looking for ability to set rate-limiting per group when scheduling new job. I saw https://github.com/taskforcesh/bullmq-pro-support/issues/1 mentioned that new options are available in Job.add(). But add() function misses those new options and allows only group id (https://api.bullmq.pro/interfaces/JobsProOptions.html). Documentation https://docs.bullmq.io/bullmq-pro/groups also doesn't mention new options. This issue https://github.com/taskforcesh/bullmq-pro-support/issues/13 explains that rate-limit per group isn't supported. There's another mention in the documentation `From BullMQ 3.0 and onwards, group keys support is removed to improve global rate limit, so the information below is only valid for older versions.` and this might be related to new way to limit groups, but it doesn't state how. Could you clarify on how groups rate-limiting works and my question on the .add() interface. Thanks

**Comment by manast** [comment]
You do not define the rate limit when adding jobs, but when instantiating your workers (https://docs.bullmq.io/bullmq-pro/groups/rate-limiting): 
```
import { WorkerPro } from '@taskforcesh/bullmq-pro';

const worker = new WorkerPro('myQueue', processFn, {
    group: {
      limit: {
        max: 100,  // Limit to 100 jobs per second per group
        duration 1000,
      }
    },
    connection
});
```

Maybe you are asking if it is possible to have different rate-limit settings per group, instead of having the same setting for all of them. In this case, this feature will most likely be implemented as a dynamic rate-limit and not as an option you pass when adding jobs.

**Comment by dginzbourg** [comment]
Yes, that's the feature I'm looking for. I saw the following code [here](https://github.com/taskforcesh/bullmq-pro-support/issues/1)

```
  import { QueuePro } from 'bullmq-pro'
  
  const queue = new QueuePro();

  const job1 = await queue.add('test', { foo: 'bar1' }, {
    group: {
      id: 1,
      limit: {
       max: 250,
       duration: 3000,
      }
    },
  });
  
  const job2 = await queue.add('test', { foo: 'bar2' }, {
    group: {
      id: 2,
      limit: {
        max: 100,
        duration: 4000,
      }
    },
  });
```
is it something that was dropped or been implemented differently as you described - symmetric across all groups?

**Comment by manast** [comment]
@dginzbourg it was implemented differently. It is symmetric across all groups now. Would allowing to rate-limit inside the job processor per group solve your use case?

**Comment by dginzbourg** [comment]
Now that we have all the information :) we'll review whether it's sufficient and good or it'll be more a workaround for us. Initially we planned to allow our users to define desired throughput for 3rd party api calls (our users configure jobs with information for what 3rd party api to call). But now we might consider dynamic throttling based on the 3rd apis behavior, i.e. automatic back pressure. Need to think through and agree with Product.

**Comment by dginzbourg** [comment]
Just to assure that rate-limit special exception will not count against retry attempts + backoff policies, right?

**Comment by manast** [comment]
If a queue gets rate-limit, then a job that fails and must be retried will also be subjected to the rate limit, in other words, no processor function will be called while the queue is rate-limited.

**Comment by dginzbourg** [comment]
I meant not the failing job, but the job that was rate-limited and let's say configured with 5 attempts. I'd assume that the fact that it was rate-limited via new dynamic rate-limit mechanism (via throwing error) doesn't reduce the attempts number, ie. in this case it still has 5 attempts to fail on some other errors (rate-limiting doesn't affect the number of attempts counting).
And to your previous question, our use-case can be implemented with a new features - [group + dynamic] rate-limiting. Do you already have dates to make it available in pro version?

**Comment by manast** [comment]
@dginzbourg I am planning an implementation along these lines:
```ts
const rateLimitWorker = new WorkerPro(
  "rate-limit",
  async (job) => {
    const result = await callExternalAPIOrWhatever(job.data, job.opts.group.id);
    if (rateLimited(result)) {
      await rateLimitWorker.rateLimitByGroup(job.opts.group.id, 1000);
      throw Worker.RateLimitError();
    }
  },
  {
    connection: { host: "my.redis-host.com" },
    concurrency: 500,
    // Optional limiter options that will get overrided by the manual dynamic rate limit
    limiter: { max: 300, duration: 1000 },
  }
);
```

If this fulfills the requirements you have, we could target to deliver it by the middle of next week.

**Comment by dginzbourg** [comment]
@manast These options are for all groups (i.e. symmetric across groups), right?
` // Optional limiter options that will get overrided by the manual dynamic rate limit
    limiter: { max: 300, duration: 1000 },
`
Yes, that'd be good solution for us. Thanks

**Comment by manast** [comment]
Just an update about this feature. The feature has been implemented but we had a very stubborn test case that fails and we have been working hard to make it work. The feature will be released right after we fix the test.

**Comment by manast** [comment]
Here the documentation of the new feature: https://docs.bullmq.io/bullmq-pro/groups/rate-limiting#manual-rate-limit

**Comment by dginzbourg** [comment]
Thanks Manuel

Has the new version been released or the test is still not passing?

**Comment by manast** [comment]
Tests are passing but just waiting for an approval before we can merge and make the release. It will happen later today.

**Comment by dginzbourg** [comment]
Hi
I think the code example is incorrect for the configuration section, it's a
duplicate from the "manual rate-limiting"

**Comment by dginzbourg** [comment]
And another mistake there - 409 code should be 429

**Comment by manast** [comment]
The documentation has been fixed according to your remarks and the feature has been released: 
https://docs.bullmq.io/bullmq-pro/changelog#5.1.0-2022-11-29
