### ISSUE TITLE
API reference link to BullMQ-Pro is broken

### ISSUE THREAD

**Issue by dginzbourg** [taskforcesh/bullmq-pro-support#29]
Link to the [pro documentation](https://api.bullmq.pro/) from https://docs.bullmq.io/bullmq-pro/groups

**Comment by manast** [comment]
Thanks for reporting this. We are looking into this.

**Comment by roggervalf** [comment]
hi @dginzbourg I can see our pro documentation now https://api.docs.bullmq.io/

**Comment by dginzbourg** [comment]
It isn't Pro version, but regular bullmq. the link on points to
https://api.bullmq.pro/ which is still not available. The link you
specified doesn't include *Pro classes, e.g. WorkerOptionsPro

 [image: image.png]

**Comment by roggervalf** [comment]
hi @dginzbourg, https://api.bullmq.pro is working now

**Comment by dginzbourg** [comment]
> hi @dginzbourg, https://api.bullmq.pro is working now

Thank you for fixing that
