### ISSUE TITLE
BullMQ Import Not Working with Pro Version

### ISSUE THREAD

**Issue by lukepolo** [taskforcesh/bullmq-pro-support#3]
## Problem

```
src/queue/BullMQQueue.ts:12:37 - error TS2307: Cannot find module 'bullmq-pro' or its corresponding type declarations.

12 import { QueuePro, WorkerPro } from "bullmq-pro";
```

![image](https://user-images.githubusercontent.com/2066668/144264289-8b8a738e-e2f1-439f-b014-fc464415c212.png)

## Steps

1. yarn add @taskforcesh/bullmq-pro
2. import { QueuePro, WorkerPro } from 'bullmq-pro';

## Version

```
  "name": "@taskforcesh/bullmq-pro",
  "version": "1.1.2",
``` 

## Misc
I did just try to go around the issue and do : 

```
import { QueuePro, WorkerPro } from "@taskforcesh/bullmq-pro/dist";

console.info("PRO", {
  QueuePro, WorkerPro
})
```

This seems to work though

```import { QueuePro, WorkerPro } from "@taskforcesh/bullmq-pro/dist/classes";```

**Comment by roggervalf** [comment]
@lukepolo thanks for reporting this, please try v1.1.4, a fix was merged

**Comment by lukepolo** [comment]
heads up your docs say this is possible

```
} from "bullmq-pro";
```

but it has to be 

```
} from "@taskforcesh/bullmq-pro";
```

**Comment by manast** [comment]
Thanks, fixed now!
