### ISSUE TITLE
Upgrade from 3.0.0 -> 5.1.9 results in script errors

### ISSUE THREAD

**Issue by hardcodet** [taskforcesh/bullmq-pro-support#34]
Hi @manast 

I performed a BullMQ upgrade, and am now seeing the following errors on the terminal:
`Script attempted to access nonexistent global variable 'activeKey'`

They just are being displayed occasionally, I assume when a task is due.

```
ReplyError: ERR Error running script (call to f_ba9d2d4b05fe899fb0c7490739b4890e6fb32da7): @user_script:265: user_script:265: Script attempted to access nonexistent global variable 'activeKey'
    at parseError (C:\...\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (C:\...\node_modules\redis-parser\lib\parser.js:302:14) {
  command: {
    name: 'evalsha',
    args: [
      'ba9d2d4b05fe899fb0c7490739b4890e6fb32da7',
      '8',
      'bull:Resivo API.PHI:stalled',
      'bull:Resivo API.PHI:wait',
      'bull:Resivo API.PHI:active',
      'bull:Resivo API.PHI:failed',
      'bull:Resivo API.PHI:stalled-check',
      'bull:Resivo API.PHI:meta',
      'bull:Resivo API.PHI:paused',
      'bull:Resivo API.PHI:events',
      '1',
      'bull:Resivo API.PHI:',
      '1672251664642',
      '30000'
    ]
  }
}
```

After one of the restarts, I also got this guy here, which was > 5000 lines long. It looks as if it took the actual scripts an argument, and didn't like it:

![image](https://user-images.githubusercontent.com/873009/209867686-d8232c43-c461-4746-ad02-aa43df2faab0.png)

**Comment by roggervalf** [comment]
hi @hardcodet , please try version 5.1.10 when get some chance

**Comment by hardcodet** [comment]
This solved the issue. Thanks for the quick turnaround, Rogger :)
