### ISSUE TITLE
npm.taskforce.sh down?

### ISSUE THREAD

**Issue by rosslavery** [taskforcesh/bullmq-pro-support#40]
Hi,

Our docker builds are failing, receiving 502 Bad Gateway errors when trying to install bullmq-pro.

Any help would be appreciated as our deploys are blocked until this is resolved 😔

```
#0 82.69 npm ERR! code E502
#0 82.69 npm ERR! 502 Bad Gateway - GET https://npm.taskforce.sh/@taskforcesh/bullmq-pro/-/@taskforcesh/bullmq-pro-5.1.2.tgz
```

**Comment by for2gles** [comment]
![image](https://user-images.githubusercontent.com/28400932/220825393-5bf680ee-a00b-4dff-b2ec-32c8b12de237.png)
I also cannot install the package because of this error.

**Comment by manast** [comment]
I just got notified about this, working on it.

**Comment by manast** [comment]
The NPM service went down after a failed pm2 auto-update. The service is restored and running normally again, sorry for the inconveniencies.
