### ISSUE TITLE
NestJS Compatibility

### ISSUE THREAD

**Issue by RavianXReaver** [taskforcesh/bullmq-pro-support#50]
Hi, I'm planning to purchase BullMQ-Pro due to limitations of the non-pro version. But before I proceed, I'd like to know the limitations that I will be facing if I were to use this with NestJS. 

I checked the official documentation for bullmq and I could find NestJS integration for [bullmq-pro]( https://docs.bullmq.io/bullmq-pro/nestjs) However, such pacakage: **taskforcesh/nestjs-bullmq-pro** does not exist in yarn repository. Could you please provide some guidance?

Thank you.

**Comment by manast** [comment]
You should be able to install it, but maybe you forgot the @ in the package name?
![image](https://github.com/taskforcesh/bullmq-pro-support/assets/95200/b8c1419d-a737-474c-9f26-9e84940c8815)

**Comment by RavianXReaver** [comment]
Thank you for the quick response. I managed to fix it by configuring the .npmrc file. I will close this issue.
