### ISSUE TITLE
Changelog for the bullmq-pro

### ISSUE THREAD

**Issue by kibertoad** [taskforcesh/bullmq-pro-support#52]
It would be great to be able to see some details about new versions being released somewhere in public access.

**Comment by manast** [comment]
You should be able to find it here: https://docs.bullmq.io/bullmq-pro/introduction

<img width="306" alt="image" src="https://github.com/taskforcesh/bullmq-pro-support/assets/95200/2755d6ab-385c-42ed-8238-09f471500945">

**Comment by manast** [comment]
Let me know if this is enough. We are planing automatic emails when new versions are released for better visibility as well.

**Comment by kibertoad** [comment]
Thanks! This is exactly what I was looking for
