### ISSUE TITLE
removeChildren support in bullmq-pro

### ISSUE THREAD

**Issue by kibertoad** [taskforcesh/bullmq-pro-support#55]
bullmq 4.6.0 supports `{ removeChildren }` parameter for `remove()` operation.

Are there any plans to sync bullmq-pro with 4.6.0? 6.0.4 still uses 4.1.0.

**Comment by roggervalf** [comment]
Hi @kibertoad, yes we plan yo do it, but we are working on local prioritized groups now, after it I can update it yo the latest base version

**Comment by kibertoad** [comment]
Thank you for the update!

**Comment by roggervalf** [comment]
Hi @kibertoad, please try version 6.2.2
