### ISSUE TITLE
Discrepancy in concurrency documentation

### ISSUE THREAD

**Issue by lb-kamilk** [taskforcesh/bullmq-pro-support#63]
Hey, I am currently testing out BullMQ pro. I noticed there seems to be a discrepancy between the in code documentation and the online documentation regarding concurrency.

The online version (https://docs.bullmq.io/bullmq-pro/groups/concurrency) states:
`
The concurrency factor is global, so in the example above, independently of the concurrency factor per worker or the number of workers that you instantiate in your application, it will never process more than 3 jobs per group at any given time.
`

However, the WorkerProOptions state:
```
/**
 * Amount of jobs that a single worker is allowed to work on
 * in parallel for a given group.
 *
 * @see {@link https://docs.bullmq.io/bullmq-pro/groups/concurrency}
 */
concurrency?: number;
```

Which one is the correct statement? Is the group concurrency global or per worker?

**Comment by manast** [comment]
The documentation is correct. It is just telling you that the concurrency factor per group is global independently on how many workers you are running in parallel. In other words, if you always want to limit to N the number of jobs that will ever be processed by a group concurrently, then this is the setting you should set.

**Comment by lb-kamilk** [comment]
Thanks for the clarification!

So it seems like the code comment would use a refreshing? Right now it suggests it's not global.
`Amount of jobs that a single worker is allowed to work on in parallel for a given group.`

"A single worker" reference makes me believe it's not global, but rather per worker.

```
export interface WorkerProOptions extends WorkerOptions {
    ttl?: number | JobTtlMap;
    group?: {
        limit?: {
            max: number;
            duration: number;
        };
        /**
         * Amount of jobs that a single worker is allowed to work on
         * in parallel for a given group.
         *
         * @see {@link https://docs.bullmq.io/bullmq-pro/groups/concurrency}
         */
        concurrency?: number;
    };
```

Hope I am not mudding the waters too much. Maybe Im missing something obvious

**Comment by manast** [comment]
Yeah, that does not look correct. I will change it asap.

**Comment by kibertoad** [comment]
I think this was already addressed and can be closed?

```ts
        /**
         * Maximum number of simultaneous jobs that the workers can handle within a specific group.
         * For instance, setting this value to 1 ensures that no more than one job from the same
         * group is processed at any given time. If this limit is not defined, there will be no
         * restriction on the number of concurrent jobs.
         *
         * @see {@link https://docs.bullmq.io/bullmq-pro/groups/concurrency}
         */
        concurrency?: number;
```
