### ISSUE TITLE
bullmq 5

### ISSUE THREAD

**Issue by lukepolo** [taskforcesh/bullmq-pro-support#65]
I noticed that 6.9.* is still on 4.17. I see there are some security fixes + performance boosts in 5. That being said, not sure all the details required to catch pro up to its base bullmq. Is there a timeline for this?

**Comment by roggervalf** [comment]
hey @lukepolo we are still working on a pr for it, we expect to have it ready probably by the end of this week

**Comment by roggervalf** [comment]
hey @lukepolo, we are still working on that pr, there are some changes we are doing not only in pro version but in base version as well to make it easier to upgrade
