### ISSUE TITLE
Consume jobs in batches

### ISSUE THREAD

**Issue by manast** [taskforcesh/bullmq-pro-support#7]
Currently, workers consume one job at a time as soon as the worker is free and there are jobs available in the "wait" list.
However, in some use cases, it is required to be able to consume jobs in batches, so that a batch of jobs are fetched from the queue atomically, processed as a batch, and then complete or failed as a batch.

There are 2 possible configurable settings for this feature:
- Consume "up" to N jobs. As soon as there are jobs, the worker will try to fetch up to N jobs, but can fetch less if there are not enough available.
- Consume "exactly" N Jobs, waits until there are at least N jobs available before fetching them, however there will be a time limit, and if timedout it will behave as in the previous case.

**Comment by saratscheff** [comment]
Is this issue outdated? It seems that batches is already implemented according to [this documentation](https://docs.bullmq.io/bullmq-pro/batches).

I got here by clicking the roadmap link in the BullMQ-Pro introduction [here](https://docs.bullmq.io/bullmq-pro/introduction).

**Comment by manast** [comment]
Yes, it is implemented already. It consumes "up to" N jobs. We should improve the automatic closing of issues when we implement new features.
