### ISSUE TITLE
Authentication with username and password instead of NPM tokens.

### ISSUE THREAD

**Issue by ksyd9821** [taskforcesh/bullmq-pro-support#70]
Hello,

for our current project, we have to install our dependencies through a private JFrog Artifactory repository. 
However, to set up this repository for the bullmq package, we would need a username and password for the authentication, as described [here](https://jfrog.com/help/r/artifactory-how-to-configure-npm-private-registry-using-npm-pat/configuring-artifactory-with-npm-pat-token).

Is it possible to generate such credentials that can be used alternatively to the current access token? 

Thank you in advance for the support!

**Comment by manast** [comment]
The access token is required for Taskforce.sh private npm repo. The user/pass you are referring to is for JFrog. In this case you would need to somehow use JFrog as a proxy for our npm repo, I am not familiar with JFrog so I am not sure how this is done, but maybe this is of some help: 
https://medium.com/@vniranjan251203/configure-and-use-proxy-for-npm-repositories-using-jfrog-artifactory-saas-4f0ddb7f5a98

**Comment by ksyd9821** [comment]
Hey @manast,

yes, we set up our JFrog Artifactory as a proxy for the private taskforce registry. Now the missing part is the authentication from our artifactory server to the private taskforce repo.
We only have the taskforce.sh access token, but we cannot use it directly on artifactory since it needs user/pass credentials to authenticate with the remote repository. 

We would like to know whether the taskforce repo supports this type of authentication. 

Thank you!

**Comment by manast** [comment]
That seems strange to me because most NPM repositories do not rely on user:password. In any case, if that is really required I am afraid it is not supported...

**Comment by ksyd9821** [comment]
Hey @manast ,

Thank you for the confirmation. We can close this issue then!
