### ISSUE TITLE
Type Incompatibility in `WorkerListener`

### ISSUE THREAD

**Issue by LuisWolf-Snapaddy** [taskforcesh/bullmq-pro-support#80]
### Description
I'm currently trying to migrate our codebase from BullMQ to the Pro version, but there appears to be a type incompatibility issue when using the `worker.on('active')` handler in the `@taskforcesh/bullmq-pro` package. The `worker.on` method expects a `Job` type, but the `Job` type is overridden by `JobPro`, causing a type mismatch.

### Steps to Reproduce

1. Import `Job` and `WorkerPro` from `@taskforcesh/bullmq-pro`.
2. Create a new `WorkerPro` instance.
3. Add an `active` event handler using `worker.on('active')`.

### Code Snippet

```ts
import { Job, WorkerPro } from "@taskforcesh/bullmq-pro";

const worker = new WorkerPro('test', async (job: Job) => {
  console.log(job.gid);
});

// With explicit type
worker.on('active', async (job: Job) => {
//                              ^-- This expects a base `Job` from `bullmq` but I can only
//                                  import a `Job` from `@taskforcesh/bullmq-pro` which is
//                                  technically a `JobPro`.
  console.log(job.gid);
});

// With inferred type
worker.on('active', async (job) => {
  console.log(job.gid);
//                ^-- There is no `gid` on a base `Job`
});
```

#### Error Messages
Explicit type
![image](https://github.com/user-attachments/assets/6ae5b524-0387-4157-b6e9-0dd5d1ef48cc)
Inferred type
![image](https://github.com/user-attachments/assets/210ba945-7dab-4674-b3ae-113456e10055)

### Environment
@taskforcesh/bullmq-pro version: `7.17.0`
Node.js version: `v20.18.0`
TypeScript version: `~4.8.4`

**Comment by manast** [comment]
Did you try importing ```JobPro``` instead of ```Job```?

**Comment by LuisWolf-Snapaddy** [comment]
Like this?

```ts
import { JobPro } from "@taskforcesh/bullmq-pro";

worker.on('active', async (job: JobPro) => {
//                              ^-- Still the same `Job` but with another name
  console.log(job.gid)
})
```

It makes no difference since `Job` is just `JobPro` again, but exported with another name. See the `index.d.ts` file:
![image](https://github.com/user-attachments/assets/8f25fead-39b6-4059-b516-d945eb1a63c0)

**Comment by manast** [comment]
It seems like we overlooked the typings for the listeners, we are going to need to make a new release to solve this, in the meanwhile if you force job to be of type Job & { gid: string }, it should work for now.
