### ISSUE TITLE
Is concurrency applied at the group level considered global when the same application is running on two or more Kubernetes (k8s) pods?

### ISSUE THREAD

**Issue by aliRQureshi** [taskforcesh/bullmq-pro-support#84]
I have two Kubernetes (k8s) pods running the same application. Is the concurrency defined at the group level is **Global**, or does each pod have its own group-level concurrency? For example, will both pods execute only total 03 jobs in parallel for the group?
```ts
import { WorkerPro } from '@taskforcesh/bullmq-pro';

const worker = new WorkerPro('myQueue', processFn, {
  group: {
    concurrency: 3, // Limit to max 3 parallel jobs per group
  },
  concurrency: 100,
  connection,
});
```

**Comment by manast** [comment]
The group concurrency is global, so 3 jobs concurrently for every group, but the worker concurrency (100 in your example) is local, so 100 max jobs concurrently per worker. It is also possible to use local group concurrency: https://docs.bullmq.io/bullmq-pro/groups/local-group-concurrency

**Comment by aliRQureshi** [comment]
@manast You mean that group level concurrency ensure that only 3 job per group will execute concurrently irrespective if there are multiple workers... right?
Because I need to ensure that for group X number of jobs should be execute concurrently if I have Y workers.

**Comment by manast** [comment]
> @manast You mean that group level concurrency ensure that only 3 job per group will execute concurrently irrespective if there are multiple workers... right?

Exactly.

**Comment by aliRQureshi** [comment]
Thanks @manast for response
