### ISSUE TITLE
[Feature Request] Worker Rate Limit without Duration [DUPLICATE FROM NON PRO REPO]

### ISSUE THREAD

**Issue by lukepolo** [taskforcesh/bullmq-pro-support#9]
You can close this feature request if you want this to be in the non pro version

But would like to see if we could make this more of a priority if possible.

https://github.com/taskforcesh/bullmq/issues/909

**Comment by manast** [comment]
Closed since this has already been implemented: https://docs.bullmq.io/bullmq-pro/groups/concurrency
